### PR TITLE
docs: add early adopters

### PR DESCRIPTION
**Pull request by EvertonSA**
- Add comment from user perspective

### CODE REVIEW

**Comment by EvertonSA** [comment]
I can adjust format if needed

**Comment by LeaveMyYard** [comment]
Hey, @EvertonSA!
Thank you so much for the testimonial! I’m happy it’s useful and working! Would it be alright to make the testimonial a little shorter? I was thinking of using this part if it’s OK:

> I used Robusta KRR in my production clusters, and it took me less than 5 minutes to get very well detailed cpu/memory recommendations. Our applications and platform tooling were discovered automatically; our kubecontext was discovered automatically; and our kube-prometheus-stack was discovered automatically.

**Comment by EvertonSA** [comment]
@LeaveMyYard ready for merge

**Review by aantn — APPROVED** [review]

**Comment by aantn** [comment]
Approved with pleasure!

**Pull request merged**
