### PR TITLE
Fix --show-cluster-name flag

### PR DESCRIPTION
**Pull request by aantn**
FYI @dgdevops

### CODE REVIEW

**Comment by dgdevops** [comment]
Hey @aantn,
I tested the changes but I cannot see the cluster name in the report.

```                                                                                                                                                                                                                                          
Simple Strategy                                                                                                                                                                                                                               
                                                                                                                                                                                                                                              
CPU request: 99.0% percentile, limit: unset                                                                                                                                                                                                   
Memory request: max + 15.0%, limit: max + 15.0%                                                                                                                                                                                               
History: 336.0 hours                                                                                                                                                                                                                          
Step: 1.25 minutes                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
All parameters can be customized. For example: `krr simple --cpu_percentile=90 --memory_buffer_percentage=15 --history_duration=24 --timeframe_duration=0.5`                                                                                  
                                                                                                                                                                                                                                              
This strategy does not work with objects with HPA defined (Horizontal Pod Autoscaler).                                                                                                                                                        
If HPA is defined for CPU or Memory, the strategy will return "?" for that resource.                                                                                                                                                          
You can override this behaviour by passing the --allow-hpa flag                                                                                                                                                                               
                                                                                                                                                                                                                                              
Learn more: https://github.com/robusta-dev/krr#algorithm                                                                                                                                                                                      
                                                                                                                                                                                                                                              
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┓
┃ Number ┃ Cluster           ┃ Namespace         ┃ Name              ┃ Pods ┃ Old Pods ┃ Type        ┃ Container         ┃ CPU Diff          ┃ CPU Requests      ┃ CPU Limits         ┃ Memory Diff ┃ Memory Requests   ┃ Memory Limits      ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━┩
│     1. │ xxxxx_xxxxxxx_xx… │ newrelic          │ nri-bundle-nri-m… │ 0    │ 0        │ Job         │ create            │                   │ 80m -> ? (No      │ 100m -> ? (No      │             │ 29Mi -> ? (No     │ 76Mi -> ? (No      │
│        │                   │                   │                   │      │          │             │                   │                   │ data)             │ data)              │             │ data)             │ data)              │
├────────┼───────────────────┼───────────────────┼───────────────────┼──────┼──────────┼─────────────┼───────────────────┼───────────────────┼───────────────────┼────────────────────┼─────────────┼──────────────────                                                                                                                                                                                    
```

**Comment by LeaveMyYard** [comment]
@dgdevops you mean you want a full name? Not just for reference?

**Comment by LeaveMyYard** [comment]
As I see from your message, there is a Cluster column

**Comment by dgdevops** [comment]
@LeaveMyYard, You are right, my bad
I thought the cluster name would be added just as a text above the chart but now I see it was added as a separate column for all workloads, cheers.

**Comment by aantn** [comment]
@dgdevops all good then? Let me know if anything else is needed.

**Review by LeaveMyYard — APPROVED** [review]

**Pull request merged**
